input { beats { port => 5044 } }

filter {
  if [log_type] =~ /^sim-/ {
    json { source => "message" target => "go_json" }
    date {
      match => ["[go_json][time]", "ISO8601"]
      target => "@timestamp"
      timezone => "Asia/Kolkata"
    }
    mutate {
      rename => {
        "[go_json][msg]"      => "app_message"
        "[go_json][level]"    => "app_level"
        "[go_json][scenario]" => "scenario"
      }
    }
    ruby {
      code => 'event.get("go_json").to_hash.each { |k,v| event.set(k,v) unless k == "time" }'
    }
    mutate { remove_field => ["go_json", "message", "host", "agent"] }
  }
}

output {
  if [log_type] == "sim-auth-brute-force"  { elasticsearch { hosts => ["http://elasticsearch:9200"] index => "sim-auth-brute-force" } }
  if [log_type] == "sim-payment-decline"   { elasticsearch { hosts => ["http://elasticsearch:9200"] index => "sim-payment-decline" } }
  if [log_type] == "sim-db-slow-query"     { elasticsearch { hosts => ["http://elasticsearch:9200"] index => "sim-db-slow-query" } }
  if [log_type] == "sim-cache-stampede"    { elasticsearch { hosts => ["http://elasticsearch:9200"] index => "sim-cache-stampede" } }
  if [log_type] == "sim-api-degradation"   { elasticsearch { hosts => ["http://elasticsearch:9200"] index => "sim-api-degradation" } }
}
